---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ia-classification
  labels:
    app: ia-classification
    app.kubernetes.io/component: ia-classification
    app.kubernetes.io/instance: ia-classification
    app.kubernetes.io/name: ia-classification
    app.kubernetes.io/part-of: intelligent-agriculture
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ia-classification
      app.kubernetes.io/component: ia-classification
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ia-classification
        app.kubernetes.io/component: ia-classification
    spec:
      containers:
        - name: ia-classification
          image: >-
            quay.io/rh-aiservices-bu/intelligent-agriculture-classification:0.0.4
          env:
            - name: INFERENCE_ENDPOINT
              value: 'http://modelmesh-serving:8008/v2/models/crops/infer'
            - name: PATHSERVICE_ENDPOINT
              value: 'http://ia-pathservice:5000'
            - name: CLASSIFICATION_ENDPOINT
              value: 'http://ia-classification:5000'
            - name: DRONE_SPEED
              value: '0.35'
            - name: TRACTOR_SPEED
              value: '0.1'
            - name: COMM_SPEED
              value: '0.75'
            - name: WEALTHY_CROP_INITIAL_PERCENTAGE
              value: '50'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: ia-classification
  labels:
    app: ia-classification
    app.kubernetes.io/component: ia-classification
    app.kubernetes.io/instance: ia-classification
    app.kubernetes.io/name: ia-classification
    app.kubernetes.io/part-of: intelligent-agriculture
spec:
  ports:
    - name: 5000-tcp
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: ia-classification
    app.kubernetes.io/component: ia-classification
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: ia-classification
  labels:
    app: ia-classification
    app.kubernetes.io/component: ia-classification
    app.kubernetes.io/instance: ia-classification
    app.kubernetes.io/name: ia-classification
    app.kubernetes.io/part-of: intelligent-agriculture
spec:
  to:
    kind: Service
    name: ia-classification
    weight: 100
  port:
    targetPort: 5000-tcp
  tls:
    termination: edge
  wildcardPolicy: None
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ia-pathservice
  labels:
    app: ia-pathservice
    app.kubernetes.io/component: ia-pathservice
    app.kubernetes.io/instance: ia-pathservice
    app.kubernetes.io/name: ia-pathservice
    app.kubernetes.io/part-of: intelligent-agriculture
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ia-pathservice
      app.kubernetes.io/component: ia-pathservice
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ia-pathservice
        app.kubernetes.io/component: ia-pathservice
    spec:
      containers:
        - name: ia-pathservice
          image: >-
            quay.io/rh-aiservices-bu/intelligent-agriculture-pathservice:0.0.3
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: ia-pathservice
  labels:
    app: ia-pathservice
    app.kubernetes.io/component: ia-pathservice
    app.kubernetes.io/instance: ia-pathservice
    app.kubernetes.io/name: ia-pathservice
    app.kubernetes.io/part-of: intelligent-agriculture
spec:
  ports:
    - name: 5000-tcp
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: ia-pathservice
    app.kubernetes.io/component: ia-pathservice
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: ia-pathservice
  labels:
    app: ia-pathservice
    app.kubernetes.io/component: ia-pathservice
    app.kubernetes.io/instance: ia-pathservice
    app.kubernetes.io/name: ia-pathservice
    app.kubernetes.io/part-of: intelligent-agriculture
spec:
  to:
    kind: Service
    name: ia-pathservice
    weight: 100
  port:
    targetPort: 5000-tcp
  tls:
    termination: edge
  wildcardPolicy: None